name: ${NAME}

services:
  php:
    image: php:8.4-fpm
    container_name: ${NAME}-fpm
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "${EXPOSE_PHP}:9000"
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini:ro
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M