name: ${NAME}

services:
  app:
    image: alpine:latest
    container_name: ${NAME}-app
    command: [ "sh", "-c", "while true; do echo 'Hello from ${NAME}-app'; sleep 10s; done" ]
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: ${NAME}-mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
